select d1.train_id as train_id_1, d3.train_id as train_id_2 , s1.station_name as start_name_1, d1.departing_time as start_time_1, d1.inner_station_id as start_id_1, s2.station_name as end_name_1, d2.arriving_time as end_time_1, d2.inner_station_id as end_id_1, s3.station_name as start_name_2, d3.departing_time as start_time_2, d3.inner_station_id as start_id_2, s4.station_name as end_name_2, d4.arriving_time as end_time_2, d4.inner_station_id as end_id_2, t1.date_id as train_departing_day_1,4 as departing_day_1, t1.date_id + d2.arriving_day as arriving_day_1, t2.date_id as train_departing_day_2, t2.date_id + d3.departing_day as departing_day_2, t2.date_id + d4.arriving_day as arriving_day_2, ((D3.departing_time_number+1440-D2.arriving_time_number)%1440 + (D2.arriving_day-D1.departing_day)*1440 + D2.arriving_time_number - D1.departing_time_number + (D4.arriving_day-D3.departing_day)*1440 + D4.arriving_time_number - D3.departing_time_number) as travel_time into temp21 from database1 as d1, database1 as d2,database1 as d3,database1 as d4, station as s1, station as s2,station as s3, station as s4, the_date as t1, the_date as t2 where d1.train_id = d2.train_id and d1.inner_station_id < d2.inner_station_id and d1.train_id not in(select train_id from temp13 ) and d3.train_id = d4.train_id and d3.inner_station_id < d4.inner_station_id and d3.train_id not in(select train_id from temp13 ) and d1.outer_station_id = s1.station_id and s1.city_name = '北京' and d2.outer_station_id = s2.station_id and s2.city_name = s3.city_name and d3.outer_station_id = s3.station_id and d4.outer_station_id = s4.station_id and s4.city_name = '上海' and (d3.departing_time_number + 1440 - d2.arriving_time_number)%1440 < 240 and (((d3.departing_time_number+1440-d2.arriving_time_number)%1440>60 and s2.station_id = s3.station_id) or ((d3.departing_time_number+1440-d2.arriving_time_number)%1440>120 and s2.station_id != s3.station_id)) and ((d3.departing_time_number>d2.arriving_time_number and t2.date_id = t1.date_id + d2.arriving_day - d3.departing_day) or (d3.departing_time_number<d2.arriving_time_number and t2.date_id = t1.date_id + D2.arriving_day  + 1 - d3.departing_day)) and t1.date_id = 3 - d1.departing_day and t2.date_id + d4.arriving_day < 6;
//
select distinct t.train_id_1,t.train_id_2,td1.departing_date_1, td2.departing_date_2, t.start_name_1,t.start_name_2,t.start_time_1,t.start_time_2,td1.arriving_date_1,td2.arriving_date_2,t.end_name_1,t.end_name_2,t.end_time_1,t.end_time_2,t.travel_time into temp25
from


select max(min) from (select min(r.tickets) from remaining_ticket as r, temp21 where r.the_day = temp21.train_departing_day_1 and r.train_id = temp21.train_id_1 and r.inner_station_id between temp21.start_id_1 + 1 and temp21.end_id_1 and r.seat_type in ('Hard_Seat');


//

drop table temp21; select t.train_id_1,t.train_id_2,t.seat_type_1,t.seat_type_2,t.start_name_1,t.start_time_1,t.end_name_1,t.end_time_1,t.departing_day_1,
t.arriving_day_1,t.price_1,t.start_name_2,t.start_time_2,t.end_name_2,t.end_time_2,t.departing_day_2,t.arriving_day_2,t.price_2,t.travel_time, min(r1.tickets) as tickets_1, min(r2.tickets) as tickets_2 into temp23 from remaining_ticket as r1,remaining_ticket as r2 ,temp22 as t where r1.inner_station_id between t.start_id_1 + 1 and t.end_id_1 and r1.the_day = t.train_departing_day_1 and r1.train_id = t.train_id_1 and r1.seat_type =  t.seat_type_1 and r2.inner_station_id between t.start_id_2 + 1 and t.end_id_2 and r2.the_day = t.train_departing_day_2 and r2.train_id = t.train_id_2 and r2.seat_type =  t.seat_type_2 group by t.train_id_1,t.train_id_2,t.seat_type_1,t.seat_type_2,t.start_name_1,t.start_time_1,t.end_name_1,t.end_time_1,t.departing_day_1,
t.arriving_day_1,t.price_1,t.start_name_2,t.start_time_2,t.end_name_2,t.end_time_2,t.departing_day_2,t.arriving_day_2,t.price_2,t.travel_time; drop table temp22; delete from temp23 where tickets_1 <=0 or tickets_2 <=0;

select t.train_id_1,t.train_id_2,t.seat_type_1,t.seat_type_2,t.start_name_1,t.start_time_1,t.end_name_1,t.end_time_1,t.price_1,t.start_name_2,t.start_time_2,t.end_name_2,t.end_time_2,t.price_2,t.travel_time, t.tickets_1, t.tickets_2,d1.actual_date as departing_date_1,d2.actual_date as arriving_date_1,d3.actual_date as departing_date_2,d4.actual_date as arriving_date_2 into temp24 from temp23 as t, the_date as d1, the_date as d2,the_date as d3,the_date as d4 where d1.date_id = t.departing_day_1 and d2.date_id = t.arriving_day_1 and d3.date_id = t.departing_day_2 and d4.date_id = t.arriving_day_2; select distinct t.train_id_1,t.train_id_2,t.departing_date_1, t.departing_date_2, t.start_name_1,t.start_name_2,t.start_time_1,t.start_time_2,t.arriving_date_1,t.arriving_date_2,t.end_name_1,t.end_name_2,t.end_time_1,t.end_time_2,t.travel_time into temp25 from temp24 as t; alter table temp25 add Min_Price decimal(5,1) default 9999.9; alter table temp25 add Min_Price_1 decimal(5,1) default 9999.9; alter table temp25 add Min_Price_2 decimal(5,1) default 9999.9;

alter table temp25 add Hard_Seat_1 integer; alter table temp25 add Hard_Seat_Price_1 decimal(5,1); update temp25 set Hard_Seat_1 = t.tickets_1, Hard_Seat_Price_1 = t.price_1 from temp24 as t where t.train_id_1 = temp25.train_id_1 and t.start_name_1 = temp25.start_name_1 and t.end_name_1 = temp25.end_name_1 and t.seat_type_1 = 'Hard_Seat'; update temp25 set Min_Price_1 = Hard_Seat_Price_1 where Min_Price_1 > Hard_Seat_Price_1; alter table temp25 add Hard_Seat_2 integer; alter table temp25 add Hard_Seat_Price_2 decimal(5,1); update temp25 set Hard_Seat_2 = t.tickets_2, Hard_Seat_Price_2 = t.price_2 from temp24 as t where t.train_id_2 = temp25.train_id_2 and t.start_name_2 = temp25.start_name_2 and t.end_name_2 = temp25.end_name_2 and t.seat_type_2 = 'Hard_Seat'; update temp25 set Min_Price_2 = Hard_Seat_Price_2 where Min_Price_2 > Hard_Seat_Price_2;

alter table temp25 add Soft_Seat_1 integer; alter table temp25 add Soft_Seat_Price_1 decimal(5,1); update temp25 set Soft_Seat_1 = t.tickets_1, Soft_Seat_Price_1 = t.price_1 from temp24 as t where t.train_id_1 = temp25.train_id_1 and t.start_name_1 = temp25.start_name_1 and t.end_name_1 = temp25.end_name_1 and t.seat_type_1 = 'Soft_Seat'; update temp25 set Min_Price_1 = Soft_Seat_Price_1 where Min_Price_1 > Soft_Seat_Price_1; alter table temp25 add Soft_Seat_2 integer; alter table temp25 add Soft_Seat_Price_2 decimal(5,1); update temp25 set Soft_Seat_2 = t.tickets_2, Soft_Seat_Price_2 = t.price_2 from temp24 as t where t.train_id_2 = temp25.train_id_2 and t.start_name_2 = temp25.start_name_2 and t.end_name_2 = temp25.end_name_2 and t.seat_type_2 = 'Soft_Seat'; update temp25 set Min_Price_2 = Soft_Seat_Price_2 where Min_Price_2 > Soft_Seat_Price_2;

alter table temp25 add Soft_Up_1 integer; alter table temp25 add Soft_Up_Price_1 decimal(5,1); update temp25 set Soft_Up_1 = t.tickets_1, Soft_Up_Price_1 = t.price_1 from temp24 as t where t.train_id_1 = temp25.train_id_1 and t.start_name_1 = temp25.start_name_1 and t.end_name_1 = temp25.end_name_1 and t.seat_type_1 = 'Soft_Up'; update temp25 set Min_Price_1 = Soft_Up_Price_1 where Min_Price_1 > Soft_Up_Price_1; alter table temp25 add Soft_Up_2 integer; alter table temp25 add Soft_Up_Price_2 decimal(5,1); update temp25 set Soft_Up_2 = t.tickets_2, Soft_Up_Price_2 = t.price_2 from temp24 as t where t.train_id_2 = temp25.train_id_2 and t.start_name_2 = temp25.start_name_2 and t.end_name_2 = temp25.end_name_2 and t.seat_type_2 = 'Soft_Up'; update temp25 set Min_Price_2 = Soft_Up_Price_2 where Min_Price_2 > Soft_Up_Price_2; alter table temp25 add Soft_Down_1 integer; alter table temp25 add Soft_Down_Price_1 decimal(5,1); update temp25 set Soft_Down_1 = t.tickets_1, Soft_Down_Price_1 = t.price_1 from temp24 as t where t.train_id_1 = temp25.train_id_1 and t.start_name_1 = temp25.start_name_1 and t.end_name_1 = temp25.end_name_1 and t.seat_type_1 = 'Soft_Down'; update temp25 set Min_Price_1 = Soft_Down_Price_1 where Min_Price_1 > Soft_Down_Price_1; alter table temp25 add Soft_Down_2 integer; alter table temp25 add Soft_Down_Price_2 decimal(5,1); update temp25 set Soft_Down_2 = t.tickets_2, Soft_Down_Price_2 = t.price_2 from temp24 as t where t.train_id_2 = temp25.train_id_2 and t.start_name_2 = temp25.start_name_2 and t.end_name_2 = temp25.end_name_2 and t.seat_type_2 = 'Soft_Down'; update temp25 set Min_Price_2 = Soft_Down_Price_2 where Min_Price_2 > Soft_Down_Price_2;

update temp25 set Min_Price = Min_Price_1+Min_Price_2; alter table temp25 drop Min_Price_1; alter table temp25 drop Min_Price_2; drop table temp24;

